### ISSUE TITLE
Getting ChatJoinRequest errors even though I don't manipulate chat join requests with my bot.

### ISSUE THREAD

**Issue by iamcosmin** [HeySreelal/televerse#108]
Getting this error whenever I try to run the dart program and it does not go away.
Interestingly, I don't even do anything related to manipulating chat join requests with my bot.
The bot is an administrator in my group, has the `Add users` privilege; some users sent join requests and they have been accepted by me but this error would not go away.

```
Unhandled exception:
type 'Null' is not a subtype of type 'Map<String, dynamic>'
#0      new ChatJoinRequest.fromJson (package:televerse/src/telegram/models/chat_join_request.dart:41:31)
#1      Update.fromJson (package:televerse/src/telegram/models/update.dart:112:29)
#2      RawAPI.getUpdates.<anonymous closure> (package:televerse/src/televerse/raw_api.dart:95:28)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#5      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#6      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#7      new List.of (dart:core-patch/array_patch.dart:47:28)
#8      ListIterable.toList (dart:_internal/iterable.dart:214:7)
#9      RawAPI.getUpdates (package:televerse/src/televerse/raw_api.dart:96:10)
<asynchronous suspension>
#10     LongPolling._poll (package:televerse/src/televerse/fetch/long_polling.dart:81:23)
<asynchronous suspension>
#11     LongPolling.start (package:televerse/src/televerse/fetch/long_polling.dart:66:7)
<asynchronous suspension>
#12     Televerse.start (package:televerse/src/televerse/televerse.dart:259:14)
<asynchronous suspension>
```

**Comment by iamcosmin** [comment]
Fix:

inside `lib/src/telegram/models/chat_join_request.dart`

```dart
  /// Creates a new [ChatJoinRequest] object from json.
  factory ChatJoinRequest.fromJson(Map<String, dynamic> json) {
    return ChatJoinRequest(
      chat: Chat.fromJson(json['chat']),
      // Here, the user retrieved from the json is null because in the api, the name is 'from', not 'user'.
      // api ref: https://core.telegram.org/bots/api#chatjoinrequest
      // Before: user: User.fromJson(json['user']),
      // After:
      user: User.fromJson(json['from']),
      date: json['date'],
      bio: json['bio'],
      inviteLink: json['invite_link'] == null
          ? null
          : ChatInviteLink.fromJson(json['invite_link']),
      userChatId: json['user_chat_id'],
    );
  }
```

**Comment by HeySreelal** [comment]
Thank you so much for raising this, sounds like a terrible bug stayed unnoticed all this time :)

I'm so happy to see you make the change 🙌

**Comment by HeySreelal** [comment]
This is now released on Televerse v1.9.12. Thank you so much for contributing to Televerse. 

I strongly hope to see you in our [Televerse discussion group](https://t.me/televersedart). 

Thanks again :)
