### ISSUE TITLE
`MessageMixin` only works for message updates. 

### ISSUE THREAD

**Issue by HeySreelal** [HeySreelal/televerse#124]
Although the `MessageContext` will be utilized for various updates such as `message`, `channel_post`, `edited_message`, and `edited_channel_post`, all the methods within `MessageMixin` relied solely on the `message`.

As a result, an error would be thrown whenever any of those methods were invoked for updates other than the `message`.

**Comment by HeySreelal** [comment]
Stack Trace when this exception has happened:

```
Unhandled exception:
Null check operator used on a null value
#0      MessageMixin._msg (package:televerse/src/televerse/context/mixins/message_mixin.dart:687:37)
#1      MessageMixin.reply (package:televerse/src/televerse/context/mixins/message_mixin.dart:28:43)
#2      main.<anonymous closure> (file:///Users/sreelalts/Desktop/dev/televersetest/bin/televersetest.dart:9:11)
#3      Televerse._onUpdate (package:televerse/src/televerse/televerse.dart:210:28)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#6      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#7      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#11     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#14     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```
